name: lcz
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.10
  - gdal=3.6.3
  - rasterio=1.3.6
  - geopandas=0.12.2
  - seaborn=0.12.2
  - dask=2023.4.1
  - h5py=3.8.0
  - scikit-learn=1.2.2
  - scikit-image=0.20.0
  - plotly=5.14.1
  - jupyterlab=3.6.3
  - pip=23.1.2
  - pip:
    - sodapy==2.2.0
    - leafmap==0.20.2
    - ipywidgets==7.7.5
    - opencv-python==4.7.0.72
    
